name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest



    steps:
      - uses: actions/checkout@master
      - name: Install nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check --verbose
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build --verbose
      - name: Run cargo build
        uses: actions-rs/cargo@v1
        with:
          command: test --verbose

